---
- name: Store Install-State of apt-proxy to dynamic_vars/initial.yml
  lineinfile:
    dest: "{{ inventory_dir }}/dynamic_vars/group/initial.yml"
    line: '_setup_apt_proxy: "true"'
    insertafter: "EOF"
    regexp: '^_setup_apt_proxy: ' 
    state: present
  run_once: true
  delegate_to: localhost
  become: no